version: '3'
services:
  web:
    build:
      context: ./myweb
      dockerfile: Dockerfile
    container_name: myweb
    ports:
      - "8080:80"
    volumes:
      - ./myweb:/var/www/html

  db:
    image: mariadb:10.4
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: detail_hobbies
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - "4306:4306"
volumes:
  db_data: